### ISSUE TITLE
Line 6 Error

### ISSUE THREAD

**Issue by GabrielWrld** [logicguy1/Discord-Nitro-Generator-and-Checker#100]
File "main.py", line 6
SyntaxError: Non-ASCII character '\xc2' in file main.py on line 7, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by logicguy1** [comment]
See https://github.com/logicguy1/Discord-Nitro-Generator-and-Checker/commit/094def3ae4b10413154a938940ab02e91db15b93
