### ISSUE TITLE
NameError: name 'notify' is not defined

### ISSUE THREAD

**Issue by InvalidAccount69** [logicguy1/Discord-Nitro-Generator-and-Checker#103]
I type a my webhook and show me this error:
Traceback (most recent call last):
  File "D:\Python\Nitro\Discord-Nitro-Generator-and-Checker\main.py", line 194, in <module>
    Gen.main()  # Run the main code
  File "D:\Python\Nitro\Discord-Nitro-Generator-and-Checker\main.py", line 102, in main
    url=notify,
NameError: name 'notify' is not defined
anyone help me?

**Comment by InvalidAccount69** [comment]
C:\Users\admin>python --version
Python 3.9.6
And i install all req

**Comment by TheSuspect-dot** [comment]
I am truly sorry for not seeing this earlier. As of now, the owner of this repository will not solve the issue, for unknown reasons, so I will try and help you.

Edit the `main.py` file, scroll down to this exact line: `if webhook is not None:`. The second line down below should look like this: `url=notify,`   change it to `url=url`.

If you do not wish to do it manually, this is the entire code, with the problem solved: 
[PasteBin]:https://pastebin.com/0pcwaMNk  
[Google Drive]:https://drive.google.com/file/d/1JRlSrDbtCEWJJLgV-cyNeCMM6u4rdZPU/view?usp=drivesdk

**Comment by logicguy1** [comment]
I truet apprechiate you heling out @TheSuspect-dot, i simpelt have not had the time avaliable to fix this, I'm currently at work and will be home in a few hours, if you want you can create a PR and I will merge it right away

**Comment by TheSuspect-dot** [comment]
> I truet apprechiate you heling out @TheSuspect-dot, i simpelt have not had the time avaliable to fix this, I'm currently at work and will be home in a few hours, if you want you can create a PR and I will merge it right away

Done. I am glad I was able to help.

**Comment by logicguy1** [comment]
This error has been resolved in the latest commit.
