### ISSUE TITLE
I can run it fine but instead of invalid I get "ERROR" what does this mean?

### ISSUE THREAD

**Issue by Aceondex** [logicguy1/Discord-Nitro-Generator-and-Checker#107]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by logicguy1** [comment]
Please fill out the form

**Comment by logicguy1** [comment]
Closed due to inactivity
