### ISSUE TITLE
i only get Invalid URLS please help

### ISSUE THREAD

**Issue by DURK69** [logicguy1/Discord-Nitro-Generator-and-Checker#108]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by logicguy1** [comment]
Please fill out the form

**Comment by wibbuffey** [comment]
because the odds of getting a valid URL are n/62^19 (where n is the number of valid URLs in existence), it is incredibly unlikely you'll ever find one
