### ISSUE TITLE
Am I an idiot or an idiot?

### ISSUE THREAD

**Issue by Kxsumi** [logicguy1/Discord-Nitro-Generator-and-Checker#109]
**Describe the bug**
SyntaxError: invalid syntax                                                                                            
 >>> py -3 -m pip install -r requirements.txt                                                                              
File "<stdin>", line 1                                                                                                   
 py -3 -m pip install -r requirements.txt     

**To Reproduce**
1. Go to 'Python'
2. Type in git clone (link)
3. Get a Syntax error. 
4.  Load GitBash.
5. Get past the Syntax error.
6. Not be able to use Python requirements
7. Get frustrated since Python doesnt even work
4. Repeat

**Expected behavior**
Python doodoo

**Screenshots**
![image](https://user-images.githubusercontent.com/96434998/147386031-ee123b04-fcdd-45d1-9950-7a79893f9a2d.png)
![image](https://user-images.githubusercontent.com/96434998/147386062-e5d3133c-4f0a-4405-ad2f-f8aa8a5c46c7.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Version [e.g. 22] 10.0.22000 build 22000

**Smartphone (please complete the following information):**

**Additional context**

**Comment by logicguy1** [comment]
Try to use `python` instead of `py -3`

**Comment by Kxsumi** [comment]
![image](https://user-images.githubusercontent.com/96434998/147388484-589e90bd-b724-4d76-afbc-1b407ab1420c.png)

**Comment by Kxsumi** [comment]
I have Python installed but apparently it can't find it

**Comment by logicguy1** [comment]
Did you add python to PATH during installation?

**Comment by Kxsumi** [comment]
> Did you add python to PATH during installation?

How would I do that?

**Comment by logicguy1** [comment]
Look it up

**Comment by wibbuffey** [comment]
> am i an idiot or an idiot?

both. for your first screenshot, you're using MSYS2 at the home directory, and obviously you didn't clone the repo to there; in the second screenshot, you're in the Python shell, so obviously shell commands won't work; and in a *followup* screenshot we observed that *because* you weren't in the directory where you cloned the repo, `requirements.txt` wouldn't exist! (and by the way, it's installed as `py` on your system, not `python`. don't know why, it's pretty weird.)

**Comment by wibbuffey** [comment]
@logicguy1 close this issue, it's clearly off-topic and is not a demonstration of an issue with the project
