### ISSUE TITLE
I always get ERROR instead of Valid or Invalid

### ISSUE THREAD

**Issue by Taburet15** [logicguy1/Discord-Nitro-Generator-and-Checker#112]
What to do

**Comment by logicguy1** [comment]
I have no clue what you mean, give some context

**Comment by Taburet15** [comment]
I have installed python, requests, then i type amount of codes (10-500) and all are ERROR, not even Invalid
![image](https://user-images.githubusercontent.com/98180615/150629590-a6094704-815c-4161-a000-b35f72dceffd.png)

**Comment by Bitcorn69** [comment]
same here

**Comment by Bitcorn69** [comment]
Its the webhook, I didn't install that package thinking it wouldn't matter but it does.

**Comment by Taburet15** [comment]
Ok, i fixed the problem, i didnt install requests.txt :/
