### ISSUE TITLE
How do i use this

### ISSUE THREAD

**Issue by kirbylover1000** [logicguy1/Discord-Nitro-Generator-and-Checker#118]
i do not know how to use this, and also i don't know what they mean by "run 'py -3 -m pip install requests'", i don't see the "py -3 -m pip install requests: file, and also i didn't use a webhook, so how do i install the module requests? i really need to know.

**Comment by saud3690** [comment]
> i do not know how to use this, and also i don't know what they mean by "run 'py -3 -m pip install requests'", i don't see the "py -3 -m pip install requests: file, and also i didn't use a webhook, so how do i install the module requests? i really need to know.

they mean open cmd and write this command run 'py -3 -m pip install requests' then it will ask yout to write another command then it will open

**Comment by logicguy1** [comment]
RTFM
