### ISSUE TITLE
0 Valid | 0 Invalid ???

### ISSUE THREAD

**Issue by saud3690** [logicguy1/Discord-Nitro-Generator-and-Checker#119]
everything run perfect but it shows me ERRORS and 0 valid | 0 invalid ???
![Annotation 2022-02-04 180059](https://user-images.githubusercontent.com/73338830/152541524-2ba92de4-ca53-4f0e-83e0-58a003d9acd2.png)

**Comment by logicguy1** [comment]
Did you follow the instruktions in the readme file?

**Comment by saud3690** [comment]
> Did you follow the instruktions in the readme file?

I did these steps from requirements and its work.
pip install colored
pip install discord_webhook
