### ISSUE TITLE
checked 100k codes and non worked

### ISSUE THREAD

**Issue by Gekummy** [logicguy1/Discord-Nitro-Generator-and-Checker#126]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Thatoneguythatcodes** [comment]
Chances are pretty slim for finding a working code. Might take days, might take weeks.

**Comment by Gekummy** [comment]
ah okay, and where does the working codes get showed?
