### ISSUE TITLE
Trojan hide in this ?

### ISSUE THREAD

**Issue by GameCreep035** [logicguy1/Discord-Nitro-Generator-and-Checker#139]
Could you please explain this ?
I can't traduct rn but... explain
![image](https://user-images.githubusercontent.com/103676650/167181654-8a666464-51fc-4c6b-b64b-047cd76a2ddf.png)

**Comment by axmyo** [comment]
script

**Comment by logicguy1** [comment]
Yeah, it's making a lot of wifi requests, read the code it's open source

**Comment by GameCreep035** [comment]
end
