### ISSUE TITLE
Can someone Help me with my issues?

### ISSUE THREAD

**Issue by Athilia** [logicguy1/Discord-Nitro-Generator-and-Checker#151]
its way to complicated to understand what i am supposed to do, what am i supposed to do with the repo and how to run it and how do i install the python packages, Could someone do a Youtube video explaining what to do, because when i searched on Youtube how to run files/install python request nothing helped me at all.

**Comment by Lavenity** [comment]
whats ur disc

**Comment by Athilia** [comment]
verya#1860
