### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by crestan1** [logicguy1/Discord-Nitro-Generator-and-Checker#162]
If I generate code it says
Input How Many Codes to Generate and Check: 5
 Error | https://discord.gift/6At2EU5DBMRo7zeqzxwUtTB
 Error | https://discord.gift/E6ukKJJI3FbXHGifCnbYLBD
 Error | https://discord.gift/6tDEZEkUH2TqhfHCMWyhv0X
 Error | https://discord.gift/m0tOw2DCQqMxEW1uZpGH7Iq
 Error | https://discord.gift/FT3ZolxRhRMKQ93HLdz0bTD

**Comment by logicguy1** [comment]
Did you install all the requrements and made sure you added Them to your PATH?

**Comment by crestan1** [comment]
> Did you install all the requrements and made sure you added Them to your PATH?

Yea still error
