### ISSUE TITLE
main.py closes automatically

### ISSUE THREAD

**Issue by thALaZy** [logicguy1/Discord-Nitro-Generator-and-Checker#17]
**Describe the bug**
yesterday I ran the nitro gen and checker overnight and in the morning it was closed

**To Reproduce**
1. Open main.py
2. turn off one monitor
3. leave it running until a certain time
4. and closes with no reason

**Expected behavior**
I would expect to run until the number is done

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro edition
 - Browser: Brave
 - Version: 1.19.90

**Comment by logicguy1** [comment]
Did you install all the requrements?

**Comment by thALaZy** [comment]
yes of course

**Comment by logicguy1** [comment]
Try and run it using the terminal and if it catches an error you can send it here

**Comment by thALaZy** [comment]
![image](https://user-images.githubusercontent.com/54885958/112134364-58db6400-8bd5-11eb-9d30-f572bbfea15b.png)

**Comment by logicguy1** [comment]
Looks like you got it to work there tell me if it crashes agein

**Comment by logicguy1** [comment]
I will close the issue for now, feel free to open a new one if the same error occurs
