### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheRedBladeClan** [logicguy1/Discord-Nitro-Generator-and-Checker#19]
Traceback (most recent call last):
  File "C:\Users\Alex\Desktop\Discord-Nitro-Gen-and-Checker-main\main.py", line
153, in <module>
    Gen.main() # Run the main code
  File "C:\Users\Alex\Desktop\Discord-Nitro-Gen-and-Checker-main\main.py", line
37, in main
    num = int(input('')) # Ask the user for the amount of codes
ValueError: invalid literal for int() with base 10: ''

**Comment by logicguy1** [comment]
Did you type a number when it asked you to?

**Comment by TheRedBladeClan** [comment]
no, I did not write anything, but if I put the webhook it does the same

**Comment by logicguy1** [comment]
You need to provide it a number before pressing enter
