### ISSUE TITLE
Invalid Codes

### ISSUE THREAD

**Issue by DarkPulse69** [logicguy1/Discord-Nitro-Generator-and-Checker#21]
All of the codes literally all the code are **Invalid**.
Or is it just for fun ;-;?

**Comment by logicguy1** [comment]
It generates a code checks if it is valid or not then goes to the next one
Not all are going to be valid

**Comment by Duplexes** [comment]
You have no proxy support so you will always get rate limited at max 5 codes.

**Comment by logicguy1** [comment]
If you want proxies you can check out the [proxy development version](https://github.com/logicguy1/Discord-Nitro-Generator-and-Checker/tree/Proxy-Development-Version)
