### ISSUE TITLE
It starts opening but immediately closes right before it asks me how many codes I want

### ISSUE THREAD

**Issue by Logman1245** [logicguy1/Discord-Nitro-Generator-and-Checker#28]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by logicguy1** [comment]
You didn't fill out the form

**Comment by logicguy1** [comment]
Closing this issue dues to inactivity
