### ISSUE TITLE
not sure if its my newbishness to python or an actual issue

### ISSUE THREAD

**Issue by aynag** [logicguy1/Discord-Nitro-Generator-and-Checker#29]
but whenever i run the progran using `py -3 `main.py` i get this response py: error: unrecognized arguments: main.py

if i could get any help with thid thatd be cool. or just make fun of me idc lmao

**Comment by logicguy1** [comment]
GIthub is not a place to make fun of new developers, try and run `python main.py` instead

**Comment by Nim1com** [comment]
or check if u were in the right directory
