### ISSUE TITLE
Some simple math.

### ISSUE THREAD

**Issue by xPolar** [logicguy1/Discord-Nitro-Generator-and-Checker#30]
Not a bug report of any form or etc, just wanted to let you know of how incredibly low it is to get a valid nitro code, considering that there's only a few thousand valid ones at a time due to the 48 hour expiration period the chances are already astronomically low, and then each code is 16 characters long with 62 different possibilities resulting in the chances of getting a valid code being 1 in 62^62*16 or 2.14983303224e+112. The only thing you're doing with this code is wasting your CPU, memory, and etc as well as having Discord flag your IP address for sending thousands upon thousands of requests to check for a valid nitro code.

**Comment by logicguy1** [comment]
Yeah I know I did the math myself
