### ISSUE TITLE
colored

### ISSUE THREAD

**Issue by HEYM8PT** [logicguy1/Discord-Nitro-Generator-and-Checker#33]
Traceback (most recent call last):
  File "C:\Users\Z3Z4\The-all-in-one-discord-tool\main.py", line 1, in <module>
    from colored import fg, bg, attr
ModuleNotFoundError: No module named 'colored'
>>> 

yelp

**Comment by logicguy1** [comment]
You need to install colored, it is a requrement

**Comment by jaredgoodman03** [comment]
Should this be added to the documentation?

**Comment by logicguy1** [comment]
Oh yeah you are right I will add that tomorrow thanks
