### ISSUE TITLE
file with success codes

### ISSUE THREAD

**Issue by AndyIshereBoi** [logicguy1/Discord-Nitro-Generator-and-Checker#35]
**Is your feature request related to a problem? Please describe.**
no, but i would like a file where it would put all working nitro codes.
**Describe the solution you'd like**
a file that gets made where it will store working codes

**Describe alternatives you've considered**
i was thinking of making something that will just copy and paste the like that was a success into the file
**Additional context**

**Comment by logicguy1** [comment]
It already does that
