### ISSUE TITLE
This is a scam!

### ISSUE THREAD

**Issue by FlamptX** [logicguy1/Discord-Nitro-Generator-and-Checker#36]
It would steal my token if I ran it. I saw the hidden modules folder. DO NOT RUN THIS!

**Comment by logicguy1** [comment]
What? You cant even do that lmao can you elaborate with a bit of proof?

**Comment by logicguy1** [comment]
Oops

**Comment by BRUHWHY123** [comment]
LOL

**Comment by Supermanbatman2726** [comment]
But can I have a proof of working?

**Comment by Bennitenni111** [comment]
This generates random string of codes, flamp can you define "hidden modules" also??

**Comment by nichevulcan20** [comment]
gtfo youre a token grabber nerd what did you think? everyone, dont use it

**Comment by MattiasMoenster2019** [comment]
Idk if discord limits the use of the nitro code api https://discordapp.com/api/v6/entitlements/gift-codes 
That would be the only problem as far as I can see
Also, no this does not have a fucking token logger u dumb fuk
It is OPEN SOURCE
If you don't know how to look for a token logger in Python just don't deal with shit like this.

**Comment by logicguy1** [comment]
Lmao

**Comment by NgLamVN** [comment]
Do you think a OPEN SOURCE software have some hIddEn mOdUnLeS ?

**Comment by nickjayr** [comment]
hidden=/=open source,lmao

**Comment by V4NSH4J** [comment]
LMFAO

**Comment by godzopaf** [comment]
> gtfo youre a token grabber nerd what did you think? everyone, dont use it

can you elaborate lol

**Comment by logicguy1** [comment]
Lmao

**Comment by logicguy1** [comment]
Yeah no
