### ISSUE TITLE
U guys know that after many tentatives discord api block u to test gifts

### ISSUE THREAD

**Issue by ySnock404** [logicguy1/Discord-Nitro-Generator-and-Checker#38]
normal mensage from discord api: {"message": "Unknown Gift Code", "code": 10038}

message before 5 min of this python: 

{
  "global": false, 
  "message": "You are being rate limited.", 
  "retry_after": 600000
}

**Comment by logicguy1** [comment]
Yes, I know please check the closed issues next time
