### ISSUE TITLE
i get how to make it working ?

### ISSUE THREAD

**Issue by Noedelss** [logicguy1/Discord-Nitro-Generator-and-Checker#40]
Module discord_webhook not installed, to install run 'py -3 -m pip install discord_webhook'
Press enter to exit
![image](https://user-images.githubusercontent.com/80974924/115031255-3da7ff80-9ec8-11eb-86ef-58713d78c045.png)

**Comment by Noedelss** [comment]
yeah i have installt it but its not working

**Comment by Noedelss** [comment]
pls help me my discord is

**Comment by Noedelss** [comment]
noedelsoep_#0010

**Comment by Noedelss** [comment]
noedelsoep_ 0010

**Comment by logicguy1** [comment]
What have you tried so far

**Comment by Noedelss** [comment]
do like open a cmd in that file end do py -3 -m pip install discord_webhook
en than i get this 
![image](https://user-images.githubusercontent.com/80974924/115060914-b919a900-9ee8-11eb-879a-7994ae329e2a.png)

**Comment by Noedelss** [comment]
why is the webhook not working

**Comment by Leunamme-00** [comment]
> do like open a cmd in that file end do py -3 -m pip install discord_webhook
> en than i get this
> ![image](https://user-images.githubusercontent.com/80974924/115060914-b919a900-9ee8-11eb-879a-7994ae329e2a.png)

it says u alrdy have the libary installed

**Comment by logicguy1** [comment]
Alright i will close this issue due to inactivity
