### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by 5alidshammout** [logicguy1/Discord-Nitro-Generator-and-Checker#41]
```
Results:
 Valid: 0
 Invalid: 500
```

this is what I had after 3 mins waiting, it's not working

**Comment by 5alidshammout** [comment]
@Sebbl0508 @logicguy1 @Bennitenni111 can anyone help me please

**Comment by logicguy1** [comment]
It seraches for valid codes, not all will be valid

**Comment by 5alidshammout** [comment]
@logicguy1 I know, but why it displays invalid codes

**Comment by logicguy1** [comment]
Why shouldn't it

**Comment by 5alidshammout** [comment]
To my mind, It's going to be cleaner if you done what is in #34

**Comment by logicguy1** [comment]
Yeah i might work on a layout chance thank you for the suggestion
