### ISSUE TITLE
pls make version without checker

### ISSUE THREAD

**Issue by TerminalPR0** [logicguy1/Discord-Nitro-Generator-and-Checker#43]
Hi. I'm enjoying your gen. Would you make a version with webhook support but no checker?

**Comment by TerminalPR0** [comment]
also I make a heroku hosting version, check it?

**Comment by TerminalPR0** [comment]
This:

**Comment by logicguy1** [comment]
> Hi. I'm enjoying your gen. Would you make a version with webhook support but no checker?

I don't understand why you would need webhook support and no checker?

**Comment by TerminalPR0** [comment]
I'm will make a free and paid ver of gen

**Comment by TerminalPR0** [comment]
Free ver - no checker
Paid - with

**Comment by TerminalPR0** [comment]
I can invite you in my server, if u will :(

**Comment by TerminalPR0** [comment]
btw, I can a create in your repo folder with your gen with heroku hosting support?

**Comment by logicguy1** [comment]
No
