### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by Smiggle2406** [logicguy1/Discord-Nitro-Generator-and-Checker#45]
what do i type to make it use webhook?

**Comment by Smiggle2406** [comment]
and why is this happening?
![Uploading Screen Shot 2021-04-20 at 8.32.48 pm.png…]()

**Comment by Smiggle2406** [comment]
<img width="682" alt="Screen Shot 2021-04-20 at 8 32 48 pm" src="https://user-images.githubusercontent.com/82069717/115382179-bafca880-a217-11eb-86e7-029a078ca6a3.png">

**Comment by logicguy1** [comment]
It may happen because of connection issues etc

**Comment by logicguy1** [comment]
> what do i type to make it use webhook?

Just the webhook url

**Comment by ToxicWolfYT-alt** [comment]
i typed the webhook url and it didnt do anything then i pressed enter and it just continued like it would without webhook

**Comment by logicguy1** [comment]
Yeah when it gets a valid code it will notify you in discord

**Comment by ToxicWolfYT-alt** [comment]
ooohhh kk

**Comment by ToxicWolfYT-alt** [comment]
ohhh kk
