### ISSUE TITLE
Nice file names

### ISSUE THREAD

**Issue by Sarptra** [logicguy1/Discord-Nitro-Generator-and-Checker#47]
![image](https://user-images.githubusercontent.com/51697170/117310329-d90b0f80-ae8b-11eb-8e9a-a3a100be01e6.png)
Token grabberpy tf?

**Comment by logicguy1** [comment]
Your in the wrong repo lol

**Comment by Sarptra** [comment]
Nope thats just modules folder

**Comment by logicguy1** [comment]
Yeah but there is no modules folder in this repo, it is the nitro gen and checker

**Comment by logicguy1** [comment]
![image](https://user-images.githubusercontent.com/56993729/117404099-a142ad00-af09-11eb-8555-1101d9643c30.png)
As you can see, there is no modules folder

**Comment by Sarptra** [comment]
After install modules nevermind thats can be but not used in any code so there is no problem
