### ISSUE TITLE
.exe file

### ISSUE THREAD

**Issue by anshmehta7x** [logicguy1/Discord-Nitro-Generator-and-Checker#49]
use pyinstaller or py2exe to make the file into an executable. this will allow people to use the generator without python installed

**Comment by 5alidshammout** [comment]
Nice idea 💡

**Comment by HellBri8nger** [comment]
> use pyinstaller or py2exe to make the file into an executable. this will allow people to use the generator without python installed

shouldn't this be on pull requests?

**Comment by Fisheiyy** [comment]
> > use pyinstaller or py2exe to make the file into an executable. this will allow people to use the generator without python installed
> 
> shouldn't this be on pull requests?

no for a pull request you have to make a change to the code

**Comment by AstroNaut244** [comment]
It was a too good idea soo... I just did it! Check out fast! https://github.com/aimaster123/Discord-Nitro-Generator-and-Checker

**Comment by Fisheiyy** [comment]
if you want it to actually be added to this repository you would have to make a PR and it would not be accepted because you dont retain any of the actual source files, maybe make a folder called executables with all the original source code still around it?

> It was a too good idea soo... I just did it! Check out fast! https://github.com/aimaster123/Discord-Nitro-Generator-and-Checker (this is actually from my other account)

**Comment by logicguy1** [comment]
> if you want it to actually be added to this repository you would have to make a PR and it would not be accepted because you dont retain any of the actual source files, maybe make a folder called executables with all the original source code still around it?
> 
> 
> 
> > It was a too good idea soo... I just did it! Check out fast! https://github.com/aimaster123/Discord-Nitro-Generator-and-Checker (this is actually from my other account)
> 
> 
> 
> 

All the files in the repo are the source files, the only reason it wouldn't be accepted would be because you can't verify it does not include any malware

**Comment by Fisheiyy** [comment]
> > if you want it to actually be added to this repository you would have to make a PR and it would not be accepted because you dont retain any of the actual source files, maybe make a folder called executables with all the original source code still around it?
> > > It was a too good idea soo... I just did it! Check out fast! https://github.com/aimaster123/Discord-Nitro-Generator-and-Checker (this is actually from my other account)
> 
> All the files in the repo are the source files, the only reason it wouldn't be accepted would be because you can't verify it does not include any malware

yes considering the fact that it was made by an outsider from the project and not you

**Comment by logicguy1** [comment]
And besides i dont even run windows so i cant compile it

**Comment by NanetteXD** [comment]
@logicguy1 I think you can with PyInstaller to cross-"compile" programs, anyways if you want me to cross-compile it, just ask, i'll be happy to help.
