### ISSUE TITLE
Invalid Codes

### ISSUE THREAD

**Issue by jkvhjggfhjyhgggh** [logicguy1/Discord-Nitro-Generator-and-Checker#50]
**Describe the bug**
I have checked over 100k codes and not a single one of them is valid.
**To Reproduce**
1. Run the bot.
2. See the error.

**Expected behavior**
I thought it would be a valid code after 100k attempts but there would be no valid code.
**Screenshots**
![image](https://user-images.githubusercontent.com/72280887/117821879-ffd59700-b239-11eb-90c8-0f6dc976d020.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 10]

**Comment by ahoodatheguy** [comment]
The program finds codes by inputting random strings into a url. The chance of actually getting a valid code is incredibly slim.

**Comment by logicguy1** [comment]
Thank you I'll close the issue now

**Comment by KolpixTV** [comment]
you need to check some codes haha 
![image](https://user-images.githubusercontent.com/68741965/119321923-6cf71c80-bc7d-11eb-8420-e518bb94acd8.png)
