### ISSUE TITLE
New code format

### ISSUE THREAD

**Issue by saraprc-dev** [logicguy1/Discord-Nitro-Generator-and-Checker#52]
So, Discord recently released this video: https://youtu.be/BZKz16o9rms?t=522
You can see that the codes (if I can count correctly) has 24 strings of random chars instead of 16.
Is there a way that the generator can randomly generate 16-24 characters instead of the usual 16?

I think this feature should be added.

**Comment by logicguy1** [comment]
It is pretty eazy to change the length of the gift in the code I'll send the code snippet they you need to change in a minute

**Comment by logicguy1** [comment]
By changing k you change the length 

```py

                code = "".join(random.choices( # Generate the id for the gift
                    string.ascii_uppercase + string.digits + string.ascii_lowercase,
                    k = 16
                ))```
