### ISSUE TITLE
does this work?

### ISSUE THREAD

**Issue by ImKill6r** [logicguy1/Discord-Nitro-Generator-and-Checker#57]
![image](https://user-images.githubusercontent.com/76989969/119769620-61c00e80-be80-11eb-96e5-1903a827039b.png)

I've been waiting 24 hours and it hasn't generated anything for me in a vps

**Comment by johnfromstatefarm** [comment]
![py_2021-05-27_17-23-48](https://user-images.githubusercontent.com/84944808/119912607-a8f5e000-bf10-11eb-8b62-ea15987a474a.jpg)

Yeah, same here. Think it don't work anymore :(

**Comment by gud1820** [comment]
It works, the problem is that its checking to quickly, and its not using proxys so your VPSes IP is getting blacklisted. :(

**Comment by ImKill6r** [comment]
i'm using proxies

**Comment by Fisheiyy** [comment]
> ![py_2021-05-27_17-23-48](https://user-images.githubusercontent.com/84944808/119912607-a8f5e000-bf10-11eb-8b62-ea15987a474a.jpg)
> 
> Yeah, same here. Think it don't work anymore :(

discord has a max of 50 requests or code checks per second and 10000 per 10 minutes, your ip has prob been banned from discords api for a week which means everything is invalid even if it happens to be a working code
