### ISSUE TITLE
КАК ЗАПУСТИТЬ? (how to start)

### ISSUE THREAD

**Issue by newcheat** [logicguy1/Discord-Nitro-Generator-and-Checker#61]
Как запустить я нажимаю enter и программа офается

**Comment by wotabu** [comment]
Делал все по инструкции?

**Comment by petergk888** [comment]
Я тоже не знаю

I dont know either

(
Я русский
)

**Comment by shockpast** [comment]
Возможные варианты, почему программа вылетает после Enter'a:

1 - Ты неправильно подписал в каком-то из пунктов.
2 - Отсутствие Python'a на компьютере.
3 - Переустановка Python'a.
4 - Криво скачанный модуль.
