### ISSUE TITLE
I have tried over 300 and all of them are invalid. Does anyone know a fix? :)

### ISSUE THREAD

**Issue by tbzGAMING** [logicguy1/Discord-Nitro-Generator-and-Checker#63]

**Comment by palmtrwwpy** [comment]
there not all going to work because it randomly generates letters an numbers and checks them with discord's api

**Comment by tbzGAMING** [comment]
oh thanks. I just worked out that it would take over 22 million trillion trillion trillion (about 22000000000000000000000000000000000000000000) attempts to get one correct one and that would take about 70 years + of leaving it on

**Comment by logicguy1** [comment]
No one actually knows what the odds are since we don't know how many valid codes are out there
