### ISSUE TITLE
Webhooks?

### ISSUE THREAD

**Issue by Excalizan** [logicguy1/Discord-Nitro-Generator-and-Checker#65]
hello, I'm thinking about why and how do we use webhooks for this? I mean does the script send a webhook message when there is a valid code? and should we pass the webhook URL if we want to use a webhook when the script asks for? I have questions, please help

**Comment by logicguy1** [comment]
Yeah you are right in everything

**Comment by Etan74** [comment]
it will send a weebhook messaage if u got a valid code.
