### ISSUE TITLE
Haven't found a valid code yet

### ISSUE THREAD

**Issue by ItsLunaTho** [logicguy1/Discord-Nitro-Generator-and-Checker#70]
I've been running it for some bit of time now but still haven't gotten 1 valid code.  Has anyone had any success with this and if so how long did it take? Also, I see people mentioning they added proxies, how do I add a proxy?

**Comment by sedaf5** [comment]
Bro i run it on VPS and upgrade script with my 6000+ proxylist that is alive
and upgrade the threading on his script but i run it for about 6days now nothing is valid even now

**Comment by Fisheiyy** [comment]
> I've been running it for some bit of time now but still haven't gotten 1 valid code. Has anyone had any success with this and if so how long did it take? Also, I see people mentioning they added proxies, how do I add a proxy?

dont expect a sinlge code to ever work it generates a random string of letters and numbers to try and find a working code but the chance you find a working code is over in 1 in 100 million so dont expect EVER to find a code that works and if you do you have hit the jackpot and wont again for atleast 100 million codes
