### ISSUE TITLE
Doesn't want to generate correct codes

### ISSUE THREAD

**Issue by michalpustelnik7209** [logicguy1/Discord-Nitro-Generator-and-Checker#71]
**Describe the bug**
I generated 100 links and all is invalid.

**Expected behavior**
Some of codes are correct

**Screenshots**
No screenshoots

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10.0.19043.1081

**Additional context**
Generator should ask to restart generating if all codes are incorrect and ask to save all working codes

**Comment by jaasio** [comment]
LMAO, generator over 5m 
100 is nothing

**Comment by Fisheiyy** [comment]
> **Describe the bug**
> I generated 100 links and all is invalid.
> 
> **Expected behavior**
> Some of codes are correct
> 
> **Screenshots**
> No screenshoots
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows
> * Version 10.0.19043.1081
> 
> **Additional context**
> Generator should ask to restart generating if all codes are incorrect and ask to save all working codes

your actually just stupid do you know the actual percentage that you have of getting a working code? its over 1 in 50 million dont expect a good code from just 100

**Comment by CJSparrow** [comment]
> LMAO, generator over 5m
> 100 is nothing

true

**Comment by lewis12-eng** [comment]
I did 9999999999999999999999999999999999999999

**Comment by logicguy1** [comment]
You cannot estimate the posibilaty of getting valid codes but yeah, youre not gonna get 1 in 100

**Comment by neobenedict** [comment]
> 
> 
> You cannot estimate the posibilaty of getting valid codes but yeah, youre not gonna get 1 in 100
The chance is on the order of 1 in 47,672,401,706,823,533,450,263,330,816

You will **never** generate a legitimate code using this tool. If everyone on earth (8 billion) was doing 10,000,000 checks a second it would take 18,800 years for 1 person to find a code.

**Comment by Angel4379** [comment]
Puedes poner el generador en una pagina web de replit esque no se como ejecutarlo.
