### ISSUE TITLE
I want to learn, how make animation text in Python

### ISSUE THREAD

**Issue by Romtik** [logicguy1/Discord-Nitro-Generator-and-Checker#73]
Pls, helppp, I am learn( I very want to animations in my scripts, help(0(((

**Comment by 5alidshammout** [comment]
I think this should be on [StackOverflow](https://stackoverflow.com/)

**Comment by CJSparrow** [comment]
why people keep asking this question while they have the source code

**Comment by Romtik** [comment]
> why people keep asking this question while they have the source code

I try to learn source code, but, this work, did not work(((

**Comment by CJSparrow** [comment]
bruh, just google about the library then you find a lot of explanations

**Comment by Fisheiyy** [comment]
`self.slowType("Made by: Drillenissen#4268 && Benz#8295", .02) # Print who developed the code`

**Comment by Romtik** [comment]
#pip slowprint
import slowprint
slowprint("This is text on github", 0.2) #("*text*", *speed*)
