### ISSUE TITLE
Hi please answer thanks

### ISSUE THREAD

**Issue by Xkilarge** [logicguy1/Discord-Nitro-Generator-and-Checker#74]
ok just a question is this still working i just ran it about 2000000 times and not 1 valid code and can i have the discord link

**Comment by Fisheiyy** [comment]
there is no discord you loser you will not get a working code from this only 2 million attempted codes is nothing it will easily take over 100 million to find a single working code and that would be the holy grail

**Comment by logicguy1** [comment]
Seems like the issue has been resolved thank you for the responce @Fisheiyy
