### ISSUE TITLE
Generador de NITRO

### ISSUE THREAD

**Issue by Angel4379** [logicguy1/Discord-Nitro-Generator-and-Checker#75]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by logicguy1** [comment]
Issue invalid

**Comment by Angel4379** [comment]
Hola soy nuevo como puedo usar el generador de nitro??
Responde porfa.
