### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-6: character maps to <undefined>

### ISSUE THREAD

**Issue by owenboy133** [logicguy1/Discord-Nitro-Generator-and-Checker#86]
it works fine until the very end and this error message comes up. please help

error message:UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-6: character maps to <undefined>

**Comment by logicguy1** [comment]
Been fixed, was an issue with some terminals
