### ISSUE TITLE
Git not found

### ISSUE THREAD

**Issue by BubblePlayzTHEREAL** [logicguy1/Discord-Nitro-Generator-and-Checker#91]
Every time I do "git clone https://github.com/logicguy1/Discord-Nitro-Generator-and-Checker.git" I get an error.

![image](https://user-images.githubusercontent.com/58344347/141118340-ec97eaf7-e984-48a7-8be0-2414a4975ae6.png)

**Comment by Leenati** [comment]
![image](https://user-images.githubusercontent.com/81458708/144637907-64323b64-fd4e-4a05-adeb-b8e279f45d7a.png)

**Comment by UltiRequiem** [comment]
If the Issue is solved it should be closed 😔
