### ISSUE TITLE
Not started

### ISSUE THREAD

**Issue by Bang1338** [logicguy1/Discord-Nitro-Generator-and-Checker#94]
I run a code but turn out, i have this error:
Traceback (most recent call last):
  File "main.py", line 187, in <module>
    Gen.main() # Run the main code
  File "main.py", line 59, in main                                                                                          num = int(input('')) # Ask the user for the amount of codes
ValueError: invalid literal for int() with base 10: ''

(from cmd)
Version: Python 3.8.4
              Pip [I dont remember the version but i upgraded it]
              
After discovering some code, look more like dumb guy
Please help

**Comment by tensh1hx** [comment]
`ValueError: invalid literal for int() with base 10: ''` means that you tried to convert a newline character into an integer
so i guess you tried to skip the animations by pressing enter lol
just don't press anything when the program starts, you simply can't skip the animations
then when the animation is over just write the amount of codes you want to generate and that's all

**Comment by tensh1hx** [comment]
`ValueError: invalid literal for int() with base 10: ''` means that you tried to convert a newline character into an integer
so i guess you tried to skip the animations by pressing enter
just don't press anything when the program starts, then when the animation is over just write the amount of codes you want to check, and that's all
