### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by AdvancedGP** [logicguy1/Discord-Nitro-Generator-and-Checker#98]
this is what happens when i try to open or type the commands its selling me to type
https://streamable.com/tkishu

**Comment by Sk0ipy** [comment]
u need to install what is asked, open cmd en dir to the folder with cd. and then put that command in there

**Comment by AdvancedGP** [comment]
> u need to install what is asked, open cmd en dir to the folder with cd. and then put that command in there

yeah, i was able to get it to work, but is it really possible to get a "valid code", and what happens if we connect the discord webhook?

**Comment by Sk0ipy** [comment]
i think it works, but its just being lucky. it scans for random codes. and when someone has a code, but hasnt used it other people can get it b doing random code scans. ive have been scanning over 3.000.000 codes and havnt found any

the discord webhook is when de bot finds a code. it sends a messege in the discord

**Comment by BK8000L** [comment]
> ive have been scanning over 3.000.000 codes and havnt found any

any success?

**Comment by kairei** [comment]
> u need to install what is asked, open cmd en dir to the folder with cd. and then put that command in there

I am getting this error "ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'"
What should I do?

**Comment by Sk0ipy** [comment]
> 

sadly not, just finished a 100 milion search. still nothing

**Comment by Sk0ipy** [comment]
> > u need to install what is asked, open cmd en dir to the folder with cd. and then put that command in there
> 
> I am getting this error "ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'" What should I do?

look whats in the  'requirements.txt'. and install menually
