### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by darkl0g1c** [logicguy1/Discord-Nitro-Generator-and-Checker#99]
When i open it, it runs fine and then i type in the codes and it crashes pls help

**Comment by logicguy1** [comment]
Please supply your full error

**Comment by DavidJoacaRo** [comment]
> When i open it, it runs fine and then i type in the codes and it crashes pls help

Bro just install the requirements.

**Comment by logicguy1** [comment]
Closed due to inactivity
